name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update 
          sudo apt-get install -y flex bison libfl-dev

      - name: Build the executable
        run: |
          make bin/tula-test
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          bash ./tests/run-tests.sh
        working-directory: ${{ github.workspace }}

      - name: Clean up
        run: make clean
        working-directory: ${{ github.workspace }}

